CREATE TABLE ROOM
(
    ROOM_ID          INT AUTO_INCREMENT PRIMARY KEY,
    ROOM_DESCRIPTION VARCHAR(4000)  NULL,
    ROOM_NUMBER      VARCHAR(10)    NOT NULL,
    COST_PER_DAY     DECIMAL(10, 2) NOT NULL
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(150) NOT NULL,
    SURNAME       VARCHAR(150) NOT NULL,
    EMAIL_ADDRESS varchar(200) NOT NULL,
    PHONE_NUMBER  varchar(15)  NULL
);

CREATE TABLE BOOKING (
  BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY ,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  DATE_FROM DATE NOT NULL,
  DATE_TO DATE NOT NULL ,
  CUSTOMER_ID INT NOT NULL ,
  ROOM_ID INT NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);
